export const products = [
  {
    product_name: 'Apple MacBook Pro 17"',
    color: 'Silver',
    category: 'Laptop',
    price: 2999,
    status: 'in stock',
  },
  {
    product_name: 'Microsoft Surface Pro',
    color: 'White',
    category: 'Laptop PC',
    price: 1999,
    status: 'sold',
  },
  {
    product_name: 'Magic Mouse 2',
    color: 'Black',
    category: 'Accessories',
    price: 99,
    status: 'in stock',
  },
  {
    product_name: 'Dell XPS 13',
    color: 'Silver',
    category: 'Laptop',
    price: 1299,
    status: 'in stock',
  },
  {
    product_name: 'HP Spectre x360',
    color: 'Black',
    category: 'Laptop',
    price: 1599,
    status: 'sold',
  },
  {
    product_name: 'Logitech MX Master 3',
    color: 'Gray',
    category: 'Accessories',
    price: 99,
    status: 'in stock',
  },
  {
    product_name: 'Sony WH-1000XM4',
    color: 'Black',
    category: 'Accessories',
    price: 349,
    status: 'sold',
  },
  {
    product_name: 'Asus ROG Zephyrus G14',
    color: 'White',
    category: 'Laptop',
    price: 1499,
    status: 'in stock',
  },
  {
    product_name: 'Samsung Galaxy Book Pro',
    color: 'Silver',
    category: 'Laptop',
    price: 1099,
    status: 'sold',
  },
  {
    product_name: 'Apple Magic Keyboard',
    color: 'White',
    category: 'Accessories',
    price: 99,
    status: 'in stock',
  },
  {
    product_name: 'Google Pixelbook Go',
    color: 'Black',
    category: 'Laptop',
    price: 899,
    status: 'sold',
  },
  {
    product_name: 'Lenovo ThinkPad X1 Carbon',
    color: 'Black',
    category: 'Laptop',
    price: 1799,
    status: 'in stock',
  },
  {
    product_name: 'Razer Blade 15',
    color: 'Black',
    category: 'Laptop',
    price: 2499,
    status: 'sold',
  },
  {
    product_name: 'Acer Swift 3',
    color: 'Silver',
    category: 'Laptop',
    price: 699,
    status: 'in stock',
  },
  {
    product_name: 'Jabra Elite 75t',
    color: 'Black',
    category: 'Accessories',
    price: 179,
    status: 'sold',
  },
  {
    product_name: 'Apple AirPods Pro',
    color: 'White',
    category: 'Accessories',
    price: 249,
    status: 'in stock',
  },
  {
    product_name: 'Microsoft Surface Book 3',
    color: 'Silver',
    category: 'Laptop PC',
    price: 2399,
    status: 'sold',
  },
  {
    product_name: 'LG Gram 17',
    color: 'White',
    category: 'Laptop',
    price: 1799,
    status: 'in stock',
  },
  {
    product_name: 'Corsair K95 RGB Platinum',
    color: 'Black',
    category: 'Accessories',
    price: 199,
    status: 'in stock',
  },
  {
    product_name: 'Alienware m15 R3',
    color: 'White',
    category: 'Laptop',
    price: 2999,
    status: 'sold',
  },
];
